# Generated by Django 5.1.4 on 2025-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_studentinfo_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
